In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [3]:
df=pd.read_csv('./train.csv')
print(df.columns)
df=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare','Survived']]
df.head(5)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare  Survived
0            1       3    male  22.0      1      0   7.2500         0
1            2       1  female  38.0      1      0  71.2833         1
2            3       3  female  26.0      0      0   7.9250         1
3            4       1  female  35.0      1      0  53.1000         1
4            5       3    male  35.0      0      0   8.0500         0

In [4]:
df=df.dropna()

In [5]:
X=df[df.columns[1:7]].values
y=df[df.columns[7]].values
print(X[:5,:],y[:5])

[[3 'male' 22.0 1 0 7.25]
 [1 'female' 38.0 1 0 71.2833]
 [3 'female' 26.0 0 0 7.925]
 [1 'female' 35.0 1 0 53.1]
 [3 'male' 35.0 0 0 8.05]] [0 1 1 1 0]


In [6]:
for i in np.arange(len(X)):
    if(X[i,1]=='male'):
        X[i,1]=0
    else:
        X[i,1]=1
print(X[:5,:],y[:5])

[[3 0 22.0 1 0 7.25]
 [1 1 38.0 1 0 71.2833]
 [3 1 26.0 0 0 7.925]
 [1 1 35.0 1 0 53.1]
 [3 0 35.0 0 0 8.05]] [0 1 1 1 0]


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(499, 6) (499,) (215, 6) (215,)


In [8]:
clf1=tree.DecisionTreeClassifier()
clf1=clf1.fit(X,y)
score1=clf1.score(X_test,y_test)
print(clf1.predict(X_test))
print(y_test)
print(score1)

[0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1
 1 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1
 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0
 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 1 0]
[0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1
 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1
 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 1 1 0 1 0 0
 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0
 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 0 0 0 0
 1 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 1 0]
0.986046511627907


In [ ]:
svm = SVC(kernel='poly')
svm.fit(X_train,y_train)
score2=svm.score(X_test,y_test)
print(score2)

In [9]:
clf=GaussianNB()
clf.fit(X_train,y_train)
score=clf.score(X_test,y_test)
print(score)

0.7767441860465116


In [10]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
print(knn.score(X_test,y_test))

0.641860465116279


In [11]:
df=pd.read_csv('./test.csv')
print(df.columns)

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')


In [12]:
print(type(clf1))

<class 'sklearn.tree.tree.DecisionTreeClassifier'>


In [13]:
df=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch','Fare']]

In [14]:
Xtest=df[df.columns[1:7]].values

In [15]:
print(Xtest[:3,:])

[[3 'male' 34.5 0 0 7.8292]
 [3 'female' 47.0 1 0 7.0]
 [2 'male' 62.0 0 0 9.6875]]


In [16]:
for i in np.arange(len(Xtest)):
    if(Xtest[i,1]=='male'):
        Xtest[i,1]=0
    else:
        Xtest[i,1]=1
print(Xtest[:12,:])

[[3 0 34.5 0 0 7.8292]
 [3 1 47.0 1 0 7.0]
 [2 0 62.0 0 0 9.6875]
 [3 0 27.0 0 0 8.6625]
 [3 1 22.0 1 1 12.2875]
 [3 0 14.0 0 0 9.225]
 [3 1 30.0 0 0 7.6292]
 [2 0 26.0 1 1 29.0]
 [3 1 18.0 0 0 7.2292]
 [3 0 21.0 2 0 24.15]
 [3 0 nan 0 0 7.8958]
 [1 0 46.0 0 0 26.0]]


In [27]:
np.nanmean(Xtest,axis=0)

array([2.2655502392344498, 0.36363636363636365, 30.272590361445783,
       0.4473684210526316, 0.3923444976076555, 35.6271884892086],
      dtype=object)

In [31]:
for i in np.arange(len(Xtest)):
    if(np.isnan(Xtest[i,2])):
        Xtest[i,2]=30.272590361445783
    if(np.isnan(Xtest[i,5])):
        Xtest[i,5]=35.6271884892086
print(Xtest[:12,:])

[[3 0 34.5 0 0 7.8292]
 [3 1 47.0 1 0 7.0]
 [2 0 62.0 0 0 9.6875]
 [3 0 27.0 0 0 8.6625]
 [3 1 22.0 1 1 12.2875]
 [3 0 14.0 0 0 9.225]
 [3 1 30.0 0 0 7.6292]
 [2 0 26.0 1 1 29.0]
 [3 1 18.0 0 0 7.2292]
 [3 0 21.0 2 0 24.15]
 [3 0 30.272590361445783 0 0 7.8958]
 [1 0 46.0 0 0 26.0]]


In [32]:
predict=clf1.predict(Xtest)
print(predict)

[0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0
 1 0 0 1 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0
 1 0 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 1 1 0 1 1 0 1
 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1 0
 1 1 1 1 0 0 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 0 0 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 0 1 0 1 1 0 1 0 0 0]


In [33]:
passenger=df['PassengerId']
print(passenger[:5])

0    892
1    893
2    894
3    895
4    896
Name: PassengerId, dtype: int64


In [34]:
import csv
with open('output.csv','w',newline='') as f:
    field=['PassengerId','Survived']
    writer=csv.DictWriter(f,fieldnames=field)
    writer.writeheader()
    for i in range(len(passenger)):
        writer.writerow({'PassengerId':passenger[i],'Survived':predict[i]})
        